version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    reviewers:
      - "AdrielBento"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"