name: 'Quiz'
description: 'Valida a sintaxe de um quiz'
inputs:
  files:
    description: 'Arquivos do PR'
    required: true
  token:
    description: 'token'
    required: true
  pr_number:
    description: 'Pull Request number that dispatched the workflow'
    required: true

outputs:
  result:
    description: 'Comentário'

runs:
  using: 'node16'
  main: 'dist/index.js'